# Generated by Django 4.2.5 on 2023-10-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front',
            name='test',
        ),
    ]
