# Generated by Django 4.2.5 on 2023-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_courses_options_alter_datasets_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
